steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/brooklynrail-studio:${SHORT_SHA}', '.']
  secretEnv: ['database_password', 'DB_CLIENT', 'DB_HOST', 'DB_PORT', 'DB_DATABASE', 'DB_USER', 'DB_PASSWORD', 'DATABASE_URL', 'KEY', 'SECRET', 'ADMIN_EMAIL', 'ADMIN_PASSWORD', 'NODE_ENV']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/brooklynrail-studio:$SHORT_SHA']
  secretEnv: ['database_password', 'DB_CLIENT', 'DB_HOST', 'DB_PORT', 'DB_DATABASE', 'DB_USER', 'DB_PASSWORD', 'DATABASE_URL', 'KEY', 'SECRET', 'ADMIN_EMAIL', 'ADMIN_PASSWORD', 'NODE_ENV']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'brooklynrail-studio', '--image', 'gcr.io/$PROJECT_ID/brooklynrail-studio:$SHORT_SHA', '--region', 'us-west2']
  secretEnv: ['database_password', 'DB_CLIENT', 'DB_HOST', 'DB_PORT', 'DB_DATABASE', 'DB_USER', 'DB_PASSWORD', 'DATABASE_URL', 'KEY', 'SECRET', 'ADMIN_EMAIL', 'ADMIN_PASSWORD', 'NODE_ENV']
images:
- 'gcr.io/$PROJECT_ID/brooklynrail-studio:$SHORT_SHA'
availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_ID}/secrets/database_password/versions/2
    env: 'database_password'
  - versionName: projects/${PROJECT_ID}/secrets/DB_CLIENT/versions/1
    env: 'DB_CLIENT'
  - versionName: projects/${PROJECT_ID}/secrets/DB_HOST/versions/1
    env: 'DB_HOST'
  - versionName: projects/${PROJECT_ID}/secrets/DB_PORT/versions/1
    env: 'DB_PORT'
  - versionName: projects/${PROJECT_ID}/secrets/DB_DATABASE/versions/1
    env: 'DB_DATABASE'
  - versionName: projects/${PROJECT_ID}/secrets/DB_USER/versions/1
    env: 'DB_USER'
  - versionName: projects/${PROJECT_ID}/secrets/DB_PASSWORD/versions/1
    env: 'DB_PASSWORD'
  - versionName: projects/${PROJECT_ID}/secrets/DATABASE_URL/versions/1
    env: 'DATABASE_URL'
  - versionName: projects/${PROJECT_ID}/secrets/KEY/versions/1
    env: 'KEY'
  - versionName: projects/${PROJECT_ID}/secrets/SECRET/versions/1
    env: 'SECRET'
  - versionName: projects/${PROJECT_ID}/secrets/ADMIN_EMAIL/versions/1
    env: 'ADMIN_EMAIL'
  - versionName: projects/${PROJECT_ID}/secrets/ADMIN_PASSWORD/versions/1
    env: 'ADMIN_PASSWORD'
  - versionName: projects/${PROJECT_ID}/secrets/NODE_ENV/versions/1
    env: 'NODE_ENV'