steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/${TRIGGER_NAME}:${SHORT_SHA}', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/${TRIGGER_NAME}:$SHORT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', '${TRIGGER_NAME}', '--image', 'gcr.io/$PROJECT_ID/${TRIGGER_NAME}:$SHORT_SHA', '--region', 'us-west2']
options:
  logging: CLOUD_LOGGING_ONLY
images:
  - 'gcr.io/$PROJECT_ID/${TRIGGER_NAME}:$SHORT_SHA'