version: '3'

services:
  directus:
    image: directus/directus:latest
    ports:
      - "8055:8055"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/directus
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: directus
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
