services:
  directus:
    container_name: studio
    image: directus/directus:latest
    build: .
    tty: true
    stdin_open: true
    ports:
      - "8055:8055"
    env_file:
      - .env
    volumes:
      - ./uploads:/src/uploads
      - ./extensions:/src/extensions
      - ./snapshots:/src/snapshots
      - ./sync:/src/sync
    depends_on:
      - studio-db
  studio-db:
    container_name: studio-db
    image: postgres:latest
    environment:
      POSTGRES_DB: directus
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data/database:/var/lib/postgresql/data
    ports:
      - "5433:5432"
