# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
# image list: https://hub.docker.com/r/circleci/php/tags/
#

version: '2.0'

jobs:
  deploy:
    docker:
      - image: cimg/node:18.18.0
    working_directory: ~/project
    steps:
      - checkout
      - run: node --version
      - run:
          name: Install dependencies
          command: yarn install
      - deploy:
          name: Deploy
          command: ./deploy.sh

workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy
