# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
# image list: https://hub.docker.com/r/circleci/php/tags/
#

version: '2.1'

jobs:
  deploy:
    docker:
      - image: cimg/php:8.1.23-node
    working_directory: ~/project
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo apt-get install rsync
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-
      - run: yarn install 
      - save_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
          - ./vendor
      - run: node --version
      - deploy:
          name: Deploy over SSH
          command: ./deploy.sh

workflows:
  version: 2.1
  build-deploy:
    jobs:
      - deploy
